### ISSUE TITLE
Static urls in footer

### ISSUE THREAD

**Issue by rickfo97** [UNIT3D/UNIT3D#10]
- Laravel Version: 5.4.*
- PHP Version: 7.0.22-0
- Database Driver & Version: mysql 5.7.20-0

### Description:
In "partials/footer.blade.php" view the pages section all links to "https://blutopia.xyz/p/*" and not the current sites pages. Same with the TOS.

### Steps To Reproduce:
Click on the links in the pages section of the footer

### Possible Fix:
Use route or url functions.

**Comment by HDVinnie** [comment]
I have spotted this as well and I missed it for public release. Ill have a fix pushed shortly.

**Comment by rickfo97** [comment]
Also after /landing you get redirected to "https://blutopia.xyz"

**Comment by HDVinnie** [comment]
There are a lot of changes regarding static urls that were left behind.....ill address them all in this one issue. Thanks.

**Comment by HDVinnie** [comment]
See 29c9e15441995c51c74f2e003a96f123e12a3a79

However I'm going to leave this open as there is still hard URL's in the following controllers for the automated system shouts that need to be fixed with URL/ROUTE functions.

BonusController.php
CommentController.php
ForumController.php
RequestController.php
ShoutboxContoller.php
TorrentContoller.php

There is also the one Listener:
AchievementUnlocked.php

**Comment by poppabear8883** [comment]
Aslo see https://github.com/UNIT3D/UNIT3D/commit/abd3ca2849d1f8e6817bd45bdf112c5c99774776
