### ISSUE TITLE
Dupe IP check

### ISSUE THREAD

**Issue by drt420** [UNIT3D/UNIT3D#83]
Hello
It would be better if you can add dupe ip check so that one user can register one account for one ip. Also, if single ip is using multiple accounts it should be shown on dupe ip page like it is in NexusPHP.

**Comment by HDVinnie** [comment]
Yes many use that like xbtit, u232, NexusPHP and others. We chose to leave it out because its 99% inefficient. Literally the worst system. In which case its not worth storing users IP addresses for a system that is so badly inefficient. It is way to easy to get around this system trackers use......way to easy.
